hitobito/hitobito_sbv

app/domain/sbv/export/tabular/people/people_full.rb
app/domain/veteran_years.rb
app/models/group/verein.rb
app/models/sbv/person.rb
app/views/people/_details_sbv.html.haml
config/locales/models.sbv.de.yml
lib/hitobito_sbv/wagon.rb
spec/domain/veteran_years_spec.rb

Siehe hitobito/hitobito#599
Erste Spec, um die Aktivjahre zu berechnen.

Aktivjahre als berechnetes Attribut

---

app/abilities/sbv/role_ability.rb
app/controllers/sbv/roles_controller.rb
app/helpers/sbv/roles_helper.rb
app/models/sbv/role.rb
app/views/person/history/_history_members_form_sbv.html.haml
config/locales/models.sbv.de.yml
config/locales/views.sbv.de.yml
config/routes.rb
lib/hitobito_sbv/wagon.rb
spec/controllers/roles_controller_spec.rb
spec/models/role_spec.rb

Create historic membership, refs hitobito/hitobito#602

---

app/models/sbv/person.rb
config/locales/models.sbv.de.yml

Filter people by prognostic active_years hitobito/hitobito#601

---

app/jobs/refresh_active_years_job.rb
app/models/role/mitglieder_mitglied.rb
app/models/sbv/person.rb
config/initializers/delayed_job.rb
db/migrate/20180915094905_add_active_years_to_people.rb
spec/fixtures/groups.yml
spec/models/role_spec.rb
spec/performance/active_year_performance_spec.rb

Caching für Aktivjahre

---

app/abilities/song_ability.rb
app/assets/javascripts/modules/song_counts.js.coffee
app/assets/stylesheets/hitobito/customizable/_wagon.scss
app/controllers/song_censuses_controller.rb
app/controllers/songs_controller.rb
app/decorators/song_decorator.rb
app/domain/export/tabular/song_counts/list.rb
app/helpers/concerts_helper.rb
app/models/concert.rb
app/models/song.rb
app/models/song_census.rb
app/models/song_count.rb
app/views/concerts/_actions_index.html.haml
app/views/concerts/_form.html.haml
app/views/concerts/_list.html.haml
app/views/concerts/edit.html.haml
app/views/song_counts/_form.html.haml
app/views/songs/_list.html.haml
app/views/songs/create.js.haml
app_root.rb
config/locales/models.sbv.de.yml
config/locales/views.sbv.de.yml
config/settings.yml
hitobito_sbv.gemspec
lib/hitobito_sbv/wagon.rb
spec/decorators/song_decorator_spec.rb
spec/domain/export/tabular/song_counts/list_spec.rb
spec/models/concert_spec.rb
spec/models/role_spec.rb

- Form and concerts index view adjusted
- depends on new bootstrap 4 grid (https://github.com/hitobito/hitobito/pull/653)

Suisa improvements

---

app/domain/secondary_children.rb
app/models/group/mitgliederverband.rb
app/models/group/regionalverband.rb
app/models/sbv/group.rb
app/models/sbv/subscription.rb
app/views/groups/_aside_sbv.html.haml
app/views/groups/_fields_sbv.html.haml
config/locales/models.sbv.de.yml
db/migrate/20190113115950_add_secondary_parents_to_groups.rb
lib/hitobito_sbv/wagon.rb

Einen Verein an mehreren Mitgliederverbänden anhängen können

---

app/domain/export/tabular/groups/address_list.rb
app/models/sbv/group.rb
config/locales/models.sbv.de.yml
config/locales/models.sbv.fr.yml
config/locales/models.sbv.it.yml
spec/jobs/export/subgroups_export_job_spec.rb

extends groups export

---

app/controllers/history_roles_controller.rb
app/views/person/history/_history_members_form_sbv.html.haml
spec/controllers/history_roles_controller_spec.rb

Enable setting a label on roles created on the history view

---

app/views/song_counts/_form.html.haml

Migrate FontAwesome to version 5

---

app/assets/stylesheets/hitobito/customizable/_wagon.scss
app/helpers/song_censuses_helper.rb
app/views/concerts/_actions_index.html.haml
app/views/song_censuses/_finish.html.haml
config/locales/views.sbv.de.yml
spec/helpers/song_censuses_helper_spec.rb

Button Meldeliste

---

app/controllers/events/group_participations_controller.rb
app/helpers/sbv/sheet/event.rb
app/views/events/group_participations/_list.html.haml
lib/hitobito_sbv/wagon.rb

Ich bin etwas abgewichen vom Kundenwunsch, jetzt ist es jedoch sinnvoller als vorher.
fixes #37

EMF: Ansicht Gruppenanmeldungen

---

.rubocop.yml
.travis.yml
app/controllers/events/group_participations_controller.rb
app/domain/export/tabular/group_participations/list.rb
app/domain/export/tabular/group_participations/row.rb
app/helpers/dropdown/group_participations.rb
app/helpers/group_participations_format_helper.rb
app/helpers/group_participations_helper.rb
app/jobs/export/group_participations_export_job.rb
app/models/event/group_participation.rb
app/models/event/group_participation_data.rb
app/views/events/_actions_show_sbv.html.haml
app/views/events/group_participations/_actions_index.html.haml
config/locales/views.sbv.de.yml
spec/controllers/events/group_participations_controller_spec.rb
spec/domain/export/tabular/group_participations/list_spec.rb
spec/fabricators/event_festival_fabricator.rb
spec/fixtures/groups.yml
spec/fixtures/people.yml
spec/fixtures/roles.yml

Export der Anmeldungen zum EMF

---

CHANGELOG.md
app/abilities/event/group_participation_ability.rb
app/controllers/events/group_participations_controller.rb
app/helpers/sbv/sheet/event.rb
app/views/events/group_participations/_list.html.haml
app/views/events/our_participations/_list.html.haml
spec/abilities/event/group_participation_ability_spec.rb
spec/controllers/events/group_participations_controller_spec.rb
spec/fabricators/event_festival_fabricator.rb

Organisatorenrechte nach Anmeldeschluss

---

db/migrate/20190617114700_migrate_to_superstructure.rb
spec/fixtures/event_translations.yml
spec/fixtures/events.yml

Can and should be merged once https://github.com/hitobito/hitobito/pull/1135 is merged.

Translate events

---

app/models/person/active_years.rb
spec/fabricators/historic_role_fabricator.rb
spec/models/person_spec.rb

@kronn Gibt es noch weitere Rollentypen die hier vergessen gegangen sein könnten?

Also consider historic active member roles for active_years

---

app/validators/preferred_date_validator.rb

Basically:
Adapt to new error-API, resolving deprecation
See hitobito/hitobito#1390, hitobito/hitobito#1400

Rails 6.1 for the wagon

---

README.md
app/models/group/verein.rb
app/models/sbv/group.rb
app/views/groups/_attrs_sbv.html.haml
app/views/groups/_fields_sbv.html.haml
config/locales/models.sbv.de.yml
db/migrate/20211122130045_add_manual_member_count_attrs_to_groups.rb
db/migrate/20211122130045_add_reported_members_attrs_to_groups.rb
lib/hitobito_sbv/wagon.rb
lib/tasks/manually_counted_members.rake
spec/domain/sbv/export/tabular/groups/row_spec.rb
spec/models/group/verein_spec.rb

Implement manually reported members, refs: #101

---

app/models/sbv/event.rb
config/settings.yml
lib/hitobito_sbv/wagon.rb

Activate waiting_list, messages and assignments features

---

app/domain/census_calculator.rb
app/helpers/song_censuses_helper.rb
app/views/song_censuses/_totals.html.haml

Count only active groups in census

---

app/models/sbv/role.rb
app/views/roles/_fields_sbv.html.haml
spec/controllers/history_roles_controller_spec.rb
spec/models/role_spec.rb

Merge with: https://github.com/hitobito/hitobito/pull/1739

Remove wagon specific role timestamp fields

---

app/models/sbv/group.rb
app/views/groups/_attrs_sbv.html.haml
config/locales/models.sbv.de.yml
spec/domain/sbv/export/tabular/groups/row_spec.rb
spec/models/group/verein_spec.rb

Check if manual member count is used

---

app/models/group/kreis.rb
app/models/group/kreis_geschaeftsstelle.rb
app/models/group/kreis_kontakte.rb
app/models/group/kreis_musikkommission.rb
app/models/group/kreis_vorstand.rb
config/locales/models.sbv.de.yml
db/seeds/development/0_groups.rb

Add kreis layer including seeds

---

app/helpers/sbv/dropdown/invoice_new.rb
lib/hitobito_sbv/wagon.rb

Do not show membership fee as invoice option in dropdown

---

lib/hitobito_sbv/wagon.rb

fixes https://github.com/hitobito/hitobito/issues/2387

Add recurring wagon jobs to JobManager

---

db/migrate/20250515102641_remove_festival_events.rb

They were never properly managed through hitobito.
Sentry: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76174
See #159, hitobito/hitobito_ejv#14

Remove exisiting Festivals.
